export const CITIES = [
  { name: "Paris", country: "France", region: "europe", query: "Paris France skyline" },
  { name: "Tokyo", country: "Japan", region: "east-asia", query: "Tokyo Japan cityscape" },
  { name: "New York", country: "USA", region: "north-america", query: "New York City skyline" },
  { name: "Sydney", country: "Australia", region: "oceania", query: "Sydney Australia harbour" },
  { name: "Cairo", country: "Egypt", region: "africa", query: "Cairo Egypt pyramids city" },
  { name: "Rio de Janeiro", country: "Brazil", region: "south-america", query: "Rio de Janeiro Brazil" },
  { name: "London", country: "England", region: "europe", query: "London England landmarks" },
  { name: "Dubai", country: "UAE", region: "middle-east", query: "Dubai UAE skyline" },
  { name: "Rome", country: "Italy", region: "europe", query: "Rome Italy cityscape" },
  { name: "Bangkok", country: "Thailand", region: "southeast-asia", query: "Bangkok Thailand temple city" },
  { name: "Istanbul", country: "Turkey", region: "europe", query: "Istanbul Turkey skyline" },
  { name: "Mumbai", country: "India", region: "south-asia", query: "Mumbai India gateway" },
  { name: "Shanghai", country: "China", region: "east-asia", query: "Shanghai China skyline" },
  { name: "Cape Town", country: "South Africa", region: "africa", query: "Cape Town South Africa" },
  { name: "Moscow", country: "Russia", region: "europe", query: "Moscow Russia Red Square" },
  { name: "Barcelona", country: "Spain", region: "europe", query: "Barcelona Spain Sagrada" },
  { name: "Singapore", country: "Singapore", region: "southeast-asia", query: "Singapore city skyline" },
  { name: "Marrakech", country: "Morocco", region: "africa", query: "Marrakech Morocco medina" },
  { name: "Seoul", country: "South Korea", region: "east-asia", query: "Seoul South Korea cityscape" },
  { name: "Buenos Aires", country: "Argentina", region: "south-america", query: "Buenos Aires Argentina" },
  { name: "Lisbon", country: "Portugal", region: "europe", query: "Lisbon Portugal tram city" },
  { name: "Prague", country: "Czech Republic", region: "europe", query: "Prague Czech Republic bridges" },
  { name: "Havana", country: "Cuba", region: "caribbean", query: "Havana Cuba colorful streets" },
  { name: "San Francisco", country: "USA", region: "north-america", query: "San Francisco Golden Gate" },
  { name: "Amsterdam", country: "Netherlands", region: "europe", query: "Amsterdam Netherlands canals" },
  { name: "Kyoto", country: "Japan", region: "east-asia", query: "Kyoto Japan temples" },
  { name: "Petra", country: "Jordan", region: "middle-east", query: "Petra Jordan ancient city" },
  { name: "Santorini", country: "Greece", region: "europe", query: "Santorini Greece blue domes" },
  { name: "Cusco", country: "Peru", region: "south-america", query: "Cusco Peru Machu Picchu city" },
  { name: "Jaipur", country: "India", region: "south-asia", query: "Jaipur India pink city" },
];
