export const CONFIG = {
  UNSPLASH_ACCESS_KEY: "",
  ROUNDS_PER_GAME: 5,
  OPTIONS_PER_ROUND: 4,
  UNSPLASH_BASE_URL: "https://api.unsplash.com",
  IMAGE_SIZE: "regular",
  FEEDBACK_DELAY_MS: 1500,
  IMAGE_TIMEOUT_MS: 10000,
};
